name: Unity Tests

on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
    # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Probando secreto
        run: echo ${{secrets.UNITY_EMAIL}}

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          path: ./antbox
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test Results
          path: test-results.xml
