name: Unity Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Unity
      uses: game-ci/unity-test-runner@v4
      env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        unityVersion: '2022.3.9f1'
        githubToken: ${{ secrets.TOKEN }}
        
    - name: Run Tests
      run: unity -batchmode -nographics -logFile - -runTests -projectPath . -testResults test-results.xml -testPlatform playmode
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Test Results
        path: test-results.xml
